# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/VIVADO/Plasma_Vivado_Project.cache/wt [current_project]
set_property parent.project_path D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/VIVADO/Plasma_Vivado_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_vhdl -library xil_defaultlib {
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/mlite_pack.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/cam_pkg.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/Ps2Interface.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_9.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_8.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_7.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_6.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_5.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_4.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_3.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_2.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_19.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_18.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_17.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_16.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_15.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_14.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_13.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_12.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_11.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_10.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/function_1.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/trans_hexto7seg.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/shifter.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/sequ_alu_1.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/reg_bank.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/pmodoledrgb_charmap.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/pipeline.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/pc_next.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/mux_7seg.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/mult.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/MouseCtl.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/mod_7seg.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/mem_ctrl.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/conversion.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/control.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/comb_alu_1.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/bus_mux.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/alu.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/ctrl_keyb_v2.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/vgd_bitmap_640x480.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/uart.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/ram_boot.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/pmodoledrgb_terminal.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/pmodoledrgb_sigplot.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/pmodoledrgb_nibblemap.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/pmodoledrgb_bitmap.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/mlite_cpu.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/memory_64k.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/i2c.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/dma_engine.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/ctrl_SL.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/ctrl_mouse_plasma.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/ctrl_7seg.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/coproc_4.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/coproc_3.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/coproc_2.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/CUSTOM/tsi/coproc_1.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/buttons.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/plasma.vhd
  D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/HDL/PLASMA/top_plasma.vhd
}
read_xdc D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/SYNTHESIS/nexys4_DDR.xdc
set_property used_in_implementation false [get_files D:/Users/GmHtAf/Documents/Enseirb/L2/S8/EN211_systeme_programmable/plasma_pmod/SYNTHESIS/nexys4_DDR.xdc]

synth_design -top top_plasma -part xc7a100tcsg324-1
write_checkpoint -noxdef top_plasma.dcp
catch { report_utilization -file top_plasma_utilization_synth.rpt -pb top_plasma_utilization_synth.pb }
